spring:
  data:
    redis:
      host: 192.168.199.128
      port: 6379
      password: Syhaun
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms
